"""Base configuration with stable defaults.

These settings should not change often and are safe for all environments.
"""

from pathlib import Path

# Project root directory
BASE_DIR = Path(__file__).parent.parent.absolute()

# Core settings (stable defaults)
DEFAULT_SECRET_KEY = "dev-secret-key-change-in-production"


def _sqlite_uri(path: Path) -> str:
    """Convert a Path to SQLite URI."""
    return f"sqlite:///{path.resolve().as_posix()}"


# Default database paths
DEFAULT_DB_URI = _sqlite_uri(BASE_DIR / "data" / "exam.db")
LOCAL_ADMIN_DB_URI = _sqlite_uri(BASE_DIR / "data" / "admin_local.db")

# Default directories
DEFAULT_UPLOAD_FOLDER = BASE_DIR / "app" / "static" / "uploads"
DEFAULT_LOCAL_ADMIN_UPLOAD_FOLDER = BASE_DIR / "app" / "static" / "uploads_admin"
DEFAULT_BACKUP_DIR = BASE_DIR / "backups"
DEFAULT_CACHE_DIR = BASE_DIR / "data" / "cache"
DEFAULT_REPORTS_DIR = BASE_DIR / "reports"
DEFAULT_CLASSIFIER_CACHE_PATH = BASE_DIR / "data" / "classifier_cache.json"

# Default values for common settings
DEFAULT_MAX_CONTENT_LENGTH = 100 * 1024 * 1024  # 100MB
DEFAULT_AUTO_BACKUP_KEEP = 30
DEFAULT_AUTO_CREATE_DB = False

# AI defaults
DEFAULT_GEMINI_MODEL_NAME = "gemini-2.0-flash-lite"
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 2048

# Experiment defaults
DEFAULT_RETRIEVAL_MODE = "hybrid_rrf"
DEFAULT_RRF_K = 60
DEFAULT_EMBEDDING_MODEL_NAME = "intfloat/multilingual-e5-base"
DEFAULT_EMBEDDING_DIM = 768
DEFAULT_EMBEDDING_TOP_N = 300

# HYDE defaults
DEFAULT_HYDE_ENABLED = False
DEFAULT_HYDE_AUTO_GENERATE = False
DEFAULT_HYDE_PROMPT_VERSION = "hyde_v1"
DEFAULT_HYDE_STRATEGY = "blend"
DEFAULT_HYDE_BM25_VARIANT = "mixed_light"
DEFAULT_HYDE_NEGATIVE_MODE = "stopwords"
DEFAULT_HYDE_MARGIN_EPS = 0.0
DEFAULT_HYDE_MAX_KEYWORDS = 7
DEFAULT_HYDE_MAX_NEGATIVE = 6
DEFAULT_HYDE_EMBED_WEIGHT = 0.7
DEFAULT_HYDE_EMBED_WEIGHT_ORIG = 0.3

# PDF parser
DEFAULT_PDF_PARSER_MODE = "legacy"

# Auto-Confirm V2
DEFAULT_AUTO_CONFIRM_V2_ENABLED = True
DEFAULT_AUTO_CONFIRM_V2_DELTA = 0.05
DEFAULT_AUTO_CONFIRM_V2_MAX_BM25_RANK = 5
DEFAULT_AUTO_CONFIRM_V2_DELTA_UNCERTAIN = 0.03
DEFAULT_AUTO_CONFIRM_V2_MIN_CHUNK_LEN = 200

# Context Expansion
DEFAULT_PARENT_ENABLED = False
DEFAULT_PARENT_WINDOW_PAGES = 1
DEFAULT_PARENT_MAX_CHARS = 3500
DEFAULT_PARENT_TOPK = 5
DEFAULT_SEMANTIC_EXPANSION_ENABLED = True
DEFAULT_SEMANTIC_EXPANSION_TOP_N = 6
DEFAULT_SEMANTIC_EXPANSION_MAX_EXTRA = 2
DEFAULT_SEMANTIC_EXPANSION_QUERY_MAX_CHARS = 1200

# CORS
DEFAULT_CORS_ALLOWED_ORIGINS = "http://localhost:3000"
DEFAULT_CORS_ALLOWED_ORIGINS_PROD = "https://your-domain.com"

__all__ = [
    "BASE_DIR",
    "DEFAULT_SECRET_KEY",
    "DEFAULT_DB_URI",
    "LOCAL_ADMIN_DB_URI",
    "DEFAULT_UPLOAD_FOLDER",
    "DEFAULT_LOCAL_ADMIN_UPLOAD_FOLDER",
    "DEFAULT_BACKUP_DIR",
    "DEFAULT_CACHE_DIR",
    "DEFAULT_REPORTS_DIR",
    "DEFAULT_CLASSIFIER_CACHE_PATH",
    "DEFAULT_MAX_CONTENT_LENGTH",
    "DEFAULT_AUTO_BACKUP_KEEP",
    "DEFAULT_AUTO_CREATE_DB",
    "DEFAULT_GEMINI_MODEL_NAME",
    "DEFAULT_GEMINI_MAX_OUTPUT_TOKENS",
    "DEFAULT_RETRIEVAL_MODE",
    "DEFAULT_RRF_K",
    "DEFAULT_EMBEDDING_MODEL_NAME",
    "DEFAULT_EMBEDDING_DIM",
    "DEFAULT_EMBEDDING_TOP_N",
    "DEFAULT_HYDE_ENABLED",
    "DEFAULT_HYDE_AUTO_GENERATE",
    "DEFAULT_HYDE_PROMPT_VERSION",
    "DEFAULT_HYDE_STRATEGY",
    "DEFAULT_HYDE_BM25_VARIANT",
    "DEFAULT_HYDE_NEGATIVE_MODE",
    "DEFAULT_HYDE_MARGIN_EPS",
    "DEFAULT_HYDE_MAX_KEYWORDS",
    "DEFAULT_HYDE_MAX_NEGATIVE",
    "DEFAULT_HYDE_EMBED_WEIGHT",
    "DEFAULT_HYDE_EMBED_WEIGHT_ORIG",
    "DEFAULT_PDF_PARSER_MODE",
    "DEFAULT_AUTO_CONFIRM_V2_ENABLED",
    "DEFAULT_AUTO_CONFIRM_V2_DELTA",
    "DEFAULT_AUTO_CONFIRM_V2_MAX_BM25_RANK",
    "DEFAULT_AUTO_CONFIRM_V2_DELTA_UNCERTAIN",
    "DEFAULT_AUTO_CONFIRM_V2_MIN_CHUNK_LEN",
    "DEFAULT_PARENT_ENABLED",
    "DEFAULT_PARENT_WINDOW_PAGES",
    "DEFAULT_PARENT_MAX_CHARS",
    "DEFAULT_PARENT_TOPK",
    "DEFAULT_SEMANTIC_EXPANSION_ENABLED",
    "DEFAULT_SEMANTIC_EXPANSION_TOP_N",
    "DEFAULT_SEMANTIC_EXPANSION_MAX_EXTRA",
    "DEFAULT_SEMANTIC_EXPANSION_QUERY_MAX_CHARS",
    "CORS_ALLOWED_ORIGINS",
    "CORS_ALLOWED_ORIGINS_PROD",
]
